services:
  - type: web
    name: integration-api-rest
    env: node
    buildCommand: npm install
    startCommand: node integration-api-rest.js
    envVars:
      - key: NODE_ENV
        value: production 